### ISSUE TITLE
Unable to simply create a free kubernetes cluster as stated in app

### ISSUE THREAD

**Issue by dist-sys-engineer** [ibm-cloud-docs/containers#2468]
I wasted over an hour trying to try out a simple tutorial???

UNABLE TO CREATE FREE CLUSTER

keeps indicating about an upgrade

**Comment by Nadine2016** [comment]
@dist-sys-engineer Thank you very much for your feedback and I am very sorry to hear that you were not able to create a free cluster. I assume you went through the steps in the getting started tutorial? If so, both sets of instructions for classic and VPC tutorials mention that you must have a billable account to create the cluster. You can create a free cluster, but your account must be set up as a billable account either way. 

If you followed a different set of instructions, let me know so that we can look into making this part more clear. Thank you so much!

**Comment by Nadine2016** [comment]
@dist-sys-engineer I am closing this issue for now. But definitely feel free to comment here with additional information or reopen the issue. Thank you!
