### ISSUE TITLE
--remoteServer option in set wehbook command

### ISSUE THREAD

**Issue by devexdev** [ibm-cloud-docs/containers#2470]
The commands to set an audit-webhook reference an option of `--remoteServer` on https://cloud.ibm.com/docs/containers?topic=containers-health#webhook_logdna. 

`ibmcloud ks cluster master audit-webhook set --cluster <cluster_name_or_ID> --remoteServer <http://172.21.xxx.xxx>`

This must have changed because the help for the command shows the option as `--remote-server`.  When I used `--remote-server` the command did work.

```
Incorrect Usage: flag provided but not defined: -remoteServer

NAME:
        set - Set the audit webhook configuration for a cluster's Kubernetes API server. The webhook backend forwards API server audit logs to a remote server.

USAGE:
        ibmcloud ks cluster master audit-webhook set --cluster CLUSTER [--ca-cert CERT] [--client-cert CERT] [--client-key KEY] [--remote-server SERVER] [-s]
    
PARAMETERS:
    --cluster value, -c value  Specify the cluster name or ID.
    --remote-server value      The URL or IP address for the remote logging service.
    --ca-cert value            The filepath of the CA cert used to verify the remote logging service.
    --client-cert value        The filepath for the client cert that is used to authenticate against the remote logging service.
    --client-key value         The filepath for the corresponding client key that is used to connect to the remote logging service.
    -s                         Optional: Do not show the message of the day or update reminders.

FAILED
flag provided but not defined: -remoteServer
```

**Comment by Nadine2016** [comment]
@devexdev thank you for your comment. I assume that you have the latest CLI version for IBM Cloud Kubernetes Service installed. With the latest version, our CLI syntax changed a little bit and we now do not use camelcase for the CLI options anymore. So instead of `remoteServer`, you use `remote-server` as you already mentioned. We updated the documentation accordingly and the change will go out with our next prod push, which will probably be tomorrow. 

Let me know if you have any other questions. I am closing this issue, but definitely feel free to comment here if you have more questions. Thanks again for catching that!
