### ISSUE TITLE
Could you pls clarify something in this page?

### ISSUE THREAD

**Issue by bennythejudge** [ibm-cloud-docs/containers#2473]
In 

https://cloud.ibm.com/docs/containers?topic=containers-getting-started

in 
https://cloud.ibm.com/docs/containers?topic=containers-getting-started#classic-cluster-create

it reads:

```
Make sure that you are assigned the following permissions in IBM Cloud Identity and Access Management. If you are the IBM Cloud account owner, you already have all permissions by default.
Administrator platform role for IBM Cloud Kubernetes Service at the account level.
Writer or Manager service role for IBM Cloud Kubernetes Service.
Administrator platform role for Container Registry at the account level.
Super User role or the minimum required permissions for classic infrastructure.
```

In the sentence: 
```
Administrator platform role for IBM Cloud Kubernetes Service at the account level.
```
 - what does `at the account level` mean exactly?

A second question:
Can I assign all the above rights (with the exception of Classic Infrastructure) via an Access Group? 

I have been told that the Classic Infrastructure permissions can only be applied to individual users, but what about the other permissions? Can I assign them via an Access group?
Thanks

**Comment by Nadine2016** [comment]
@bennythejudge 
When you assign permissions in IAM, you can decide to limit the permissions to a namespace, region, or a cluster. If you don't limit permissions to anything, you set the permissions on the account level. When you look at your permissions overview, you will see "All Kubernetes Cluster resources". 

Regarding the access group, your assumption is correct for classic clusters. You cannot assign classic infrastructure permissions for an access group right now. But if you want to create VPC clusters, you can assign VPC access via an access group, because VPC infrastructure is fully integrated into IAM. 

I hope this helped. Let me know if you have more questions. Thank you
