### ISSUE TITLE
IKS cluster in VPC

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/containers#2478]
Lab 0 instructions in this link is wrong:
https://cloud.ibm.com/docs/tutorials?topic=containers-vpc_ks_tutorial

Please update content from git site:
https://github.com/IBM/container-service-getting-started-wt/tree/master/Lab%201

**Comment by Rachael-Graham** [comment]
What exactly do you find that is wrong in the prerequisites for the tutorial in https://cloud.ibm.com/docs/tutorials?topic=containers-vpc_ks_tutorial ? That other tutorial that you linked is not for VPC; the tutorial in the IKS docs is exclusively for a VPC cluster

**Comment by artberger** [comment]
Thanks for your contribution. Going to close this out since we're unsure of the action. Feel free to continue the conversation with us in Slack, in the [#docs public channel](https://ibm-cloud-success.slack.com/archives/C4G8V9GS1) if you're an external user, or if you're an IBMer, in the [internal channel](https://test.cloud.ibm.com/docs/containers?topic=containers-cs_internal#internal_help).
