### ISSUE TITLE
Multi Zone cluster clarification

### ISSUE THREAD

**Issue by subbu165** [ibm-cloud-docs/containers#2484]
In the documentation given below:
https://cloud.ibm.com/docs/containers?topic=containers-ha_clusters#multizone

for a single region what greater advantage it gives or what is the exact difference between MultiZoneSingle cluster and Multiple Cluster across multiple zones in a single region. 
Because for multi zone cluster too it says:
"How is my Kubernetes master set up?
When you create a cluster in a multizone metro location, a highly available master is automatically deployed and three replicas are spread across the zones of the metro. For example, if the cluster is in dal10, dal12, or dal13 zones, the replicas of the master are spread across each zone in the Dallas multizone metro"

then what is the difference with Multi Cluster.  How we should understand the difference in benefit between the two approaches.

Also when it comes to - https://cloud.ibm.com/docs/containers?topic=containers-ha_clusters#multiple_clusters
it talks about 'single zone cities' what is mean by that. 

Please throw some light.

**Comment by Rachael-Graham** [comment]
The difference between a multizone cluster versus multiple clusters connected by a GLB is mostly requirements. You might choose multiple clusters, for example, if you have a requirement to have clusters in multiple regions instead of just within one region. If you dont have a requirement like this, it is likely simpler to have a multizone cluster in one region.

For the second question, you can find into here: https://cloud.ibm.com/docs/containers?topic=containers-regions-and-zones#zones

I hope this info doesnt come too late, but et us know @subbu165 if we can provide any more guidance
