### ISSUE TITLE
Command `ibmcloud cs cluster-config <cluster_name_or_ID>` does not work

### ISSUE THREAD

**Issue by Kool-Koder** [ibm-cloud-docs/containers#2491]
Referencing issue #2434, I am still unsure of how to fix it.

I downloaded the latest CLI from here: https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started#idt-prereq and I am running Windows.

I received the error, `FAILED
'cluster-config' is not a registered command. See 'ibmcloud cs help'.`

This is my current plugin list. Thank you.
```
ibmcloud plugin list
Listing installed plug-ins...

Plugin Name                            Version   Status
container-registry                     0.1.454
container-service/kubernetes-service   1.0.28
cloud-functions/wsk/functions/fn       1.0.39
```

**Comment by Kool-Koder** [comment]
Update 1

Clicking around on the IBM Cloud Console, I chanced upon this:
![image](https://user-images.githubusercontent.com/39305371/78639859-417e6a80-78e1-11ea-9903-e0e67ff430b6.png)

ibmcloud ks cluster config <cluster_name_or_ID>.

I'm doing this course on Cognitive Class and the lab guide there is not updated, and the image links are also broken actually. Appreciate it if you can fix it. Thanks!

**Comment by artberger** [comment]
@Kool-Koder I'm sorry that you're experiencing these issues in the Cognitive Class. Could you send me a link to the course you're using, and I'll try to hunt down how to update it?

Just FYI, the error you're seeing is because `cluster-config` is an older CLI plug-in. In the latest version of the `ibmcloud ks` CLI plug-in 1.0, we've moved away from hyphenated commands, so it'd be `cluster config`. The [CLI reference doc](https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli) is up-to-date, and you can also run the help flag (`-h` or `help` in the command like `ibmcloud ks cluster help config`) if you get stuck on a command in the future.

Thanks again for letting us know!

**Comment by Kool-Koder** [comment]
Hey @artberger, thanks for your prompt reply.

This is the Cognitive Class [link](https://cognitiveclass.ai/courses/kubernetes-course) ant this is the name of the course. `Container & Kubernetes Essentials with IBM Cloud`

Thanks!

**Comment by bhpratt** [comment]
I have alerted the internal team that manages this course that updates are needed. Thanks.

**Comment by JakobSimonsen** [comment]
Using the command:
`ibmcloud cs cluster config --cluster <cluster name>`
works

**Comment by artberger** [comment]
Thanks for following up on this @bhpratt I will close out this issue here then.
