### ISSUE TITLE
Autoscaling for kuberenetes

### ISSUE THREAD

**Issue by ramanparashar** [ibm-cloud-docs/containers#2497]
While using cluster autoscaler for kubernetes I am getting the following error. Any pointers would be helpful

{“level”:“info”,“ts”:“2020-04-12T14:40:46.757Z”,“caller”:“classic/classic_service_imp.go:380",“msg”:“Failure while executing request”,“error”:“Get https://private.us-south.containers.cloud.ibm.com/v1/clusters/bpmmlt9d0b9e8l272aag/workerpools/default: dial tcp 166.9.15.70:443: i/o timeout”}

I am getting timeout when internal call is being made.

I want to understand the helm chart for the ibm-iks-cluster-autoscaler

**Comment by artberger** [comment]
@ramanparashar sorry to hear that you're having trouble. You might try this [debugging guide](https://cloud.ibm.com/docs/containers?topic=containers-troubleshoot_cluster_autoscaler) for the cluster autoscaler. 

Because this repo is for doc issues, I'm going to close this issue out. But if you have any feedback on the docs, feel free to let us know. If you keep having trouble with the cluster autoscaler, try posting in our [Slack #cluster-autoscaler channel](https://ibm-cloud-success.slack.com/archives/CF6APMLBB (or the [internal channel ](https://ibm-argonauts.slack.com/archives/C90D3KZUL) if you're an IBMer).
