### ISSUE TITLE
Update documentation to show Hyper Protect Crypto and Key Protect similar

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/containers#2527]
With the FSS Cloud Hyper Protect Crypto service will be the main KMS system for customers.

There are multiple occurences where customers are only seeing Key Protect and this would lead them into a wrong assumtion. 

Like here
https://cloud.ibm.com/docs/containers?topic=containers-service-binding

Can we ensure that Key Protect and HPCS are used in a same way. Or use an overarching term which speaks about the IBM provdided KMS systems

**Comment by artberger** [comment]
@stschmitt thanks for raising this issue. I apologize for the late response. We have been updating our KMS support over the past few months, and I've updated the documentation in a few places, for example here: https://cloud.ibm.com/docs/containers?topic=containers-encryption#kms

We're using the term "key management service provider" and for that specific doc you linked, I updated it to that and will push out this change with the next docs prod push. I'm going to close this issue here, but if you have other comments or feedback, please feel free to share or reopen. Thanks again!
