### ISSUE TITLE
Link to private 

### ISSUE THREAD

**Issue by schoutene** [ibm-cloud-docs/containers#2544]
In below section from https://cloud.ibm.com/docs/containers?topic=containers-ca#ca_private_cluster the link to "Using the cluster autoscaler for a private network-only cluster" is referred to the same page. Shouldn't it be linked to  https://cloud.ibm.com/kubernetes/helm/iks-charts/ibm-iks-cluster-autoscaler or another document and not itsself?

_The cluster autoscaler Helm chart is available for standard classic and VPC clusters that are set up with public network connectivity. If your cluster cannot access the public network, such as a private cluster behind a firewall or a cluster with only the private service endpoint enabled, see **Using the cluster autoscaler for a private network-only cluster**. If you connect to your private cluster from a VPN, verify your connection to your cluster by running kubectl get pods._

**Comment by artberger** [comment]
@schoutene thanks for raising this issue. We recently revised our docs to remove some of the outdated Helm information, and the private Helm chart one was of those removed topics, so this section has been updated. I'm going to close this issue here, but let us know if you have any other feedback. Thanks again!
