### ISSUE TITLE
Content needs to be changed(The storage-class field must be an empty string)

### ISSUE THREAD

**Issue by sivamtkr1102** [ibm-cloud-docs/containers#2565]
From below mentioned document:

https://cloud.ibm.com/docs/containers?topic=containers-file_storage#existing_file

Step 2: Creating a persistent volume (PV) and a matching persistent volume claim (PVC)

The storage-class field must be an empty string.----"must "This seems incorrect

Sometimes we may need to configure the storageClassName on our own. The statement needs to be generic for both providing value for storageClassName and for " " string.

**Comment by derekpoindexter** [comment]
@sivamtkr1102 Thanks for the feedback. The section you have linked to here - https://cloud.ibm.com/docs/containers?topic=containers-file_storage#existing_file is specifically for static provisioning with an existing NFS. 

In the case of static provisioning, when you create your PVC, all of the configuration details like capacity and accessMode, etc must match your existing PV so that the provisioner can map to the existing disk. If the storage class field is not an empty string, or if any of the configuration details in your PVC do not match your existing PV, then a new PV is dynamically provisioned. 

If you want to create a customized storage class that you can use to dynamically provision volumes, you can find the steps and example customized storage classes here - https://cloud.ibm.com/docs/containers?topic=containers-file_storage#file_custom_storageclass
