### ISSUE TITLE
--private-vlan and --public-vlan must be specified

### ISSUE THREAD

**Issue by EddieKSpin** [ibm-cloud-docs/containers#2575]
https://cloud.ibm.com/docs/containers?topic=containers-clusters#clusters_cli_steps

The documentation suggests leaving the private-vlan and public-vlan empty but if 
private-vlan exsists in the zone you can not leave public-vlan empty (Incorrect Usage. When you specify a private VLAN, you must also specify either the '--public-vlan' flag or the '--private-only' flag.) 

Users can not delete private-vlan and the cli will throw (You must specify a private VLAN for worker node connectivity. (E6967)) 
when not specified nor will it automatically create a new one.

**Comment by Rachael-Graham** [comment]
Interesting. I see what you are saying... that if you DO have a private vlan in a zone, you must specify that in the --private-vlan. but if you do NOT have the matching public vlan in that zone, the CLI prevents you from omitting the --public-vlan flag in order to have a public vlan created for you.

Am I understanding that correctly?

If so, I do not know if our API can handle that. For now I would suggest that you create the public vlan (https://cloud.ibm.com/classic/network/vlans) in the same zone as the private vlan, and then specify the vlans in the --public-vlan and --private-vlan flags

**Comment by EddieKSpin** [comment]
Yes, pretty much. 
Not to side track too much but I found this out while following along the creation step. 
A note that the documentation only pertains to first time creation of a cluster in region would be helpful.
As [this section](https://cloud.ibm.com/docs/containers?topic=containers-subnets#basics) mentions it seems any subsequent attempts will fail without much explanation.
`IBM Cloud infrastructure manages the VLANs that are automatically provisioned when you create your first cluster in a zone. If you let a VLAN become unused, such as by removing all worker nodes from a VLAN, IBM Cloud infrastructure reclaims the VLAN. After, if you need a new VLAN, contact IBM Cloud support.`

**Comment by Rachael-Graham** [comment]
I agree. I'll update the doc to have a step for checking VLANs and potentially creating a matching vlan if only 1 type (pub or priv) exists in that zone.
