### ISSUE TITLE
Doc issue with "Controlling traffic with ACLs" -- customer impact -- please prioritize

### ISSUE THREAD

**Issue by EliahuBen-Reuven** [ibm-cloud-docs/containers#2577]
Please see this issue: https://github.ibm.com/cloudlab/internal-docs/issues/1475

**Note:** @jmiddle asked to prioritize this issue. "We have open cases waiting for confirmation the documentation is accurate."

**Comment by Rachael-Graham** [comment]
"The port rules in the UI section conflict with the CLI section and cause the last 'deny all' rule to need to be 'allow all'"

"the documentation in the UI section appears to conflict with the CLI section and may be wrong"

**Comment by Rachael-Graham** [comment]
The [console steps](https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_ui) and [CLI steps](https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_cli) have been updated. In particular I believe the directionality of the ports was incorrect, so that has been updated. I will close this issue, but please re-open if you are still having issues or have other questions!
