### ISSUE TITLE
We suspect 2 additional network ACL rules are needed when all subnets in the cluster use the same network ACL

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/containers#2581]
In one support case, we found that a customer who set up a cluster with 3 subnets, and assigned the same network ACL to all three subnets, using the exact rules documented here:

https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls

... they were unable to access their Openshift Console.  It was only when we added a new inbound rule and a new outbound rule to the network ACL that things started working properly.  Here are the two rules found in the documentation:

INBOUND:
Allow incoming traffic requests to apps that run on your worker nodes. | Allow | TCP | Any | - | Any | 30000 - 32767 | After 3

OUTBOUND:
Allow incoming traffic requests to apps that run on your worker nodes. | Allow | TCP | Any | 30000 - 32767 | Any | - | After 3

The INBOUND rule sets TCP ports 30000-32767 in the DESTINATION field.  The OUTBOUND rule sets TCP ports 30000-32767 in the SOURCE field.  In a normal cluster, this appears to be sufficient.  

But if all the subnets in the cluster use the same network ACL, we found in testing we need to set an additional INBOUND rule that sets TCP ports 30000-32767 in the SOURCE field, and an additional OUTBOUND rule that sets TCP ports 30000-32767 in the DESTINATION field.  The end result looks like this:

INBOUND:
Rule Priority Allow/Deny Protocol Source Destination
10 Allow TCP Any IP, any port Any IP, ports 30000-32767
11 Allow TCP Any IP, ports 30000-32767 Any IP, any port
OUTBOUND:
Rule Priority Allow/Deny Protocol Source Destination
10 Allow TCP Any IP, ports 30000-32767 Any IP, any port
11 Allow TCP Any IP, any port Any IP, ports 30000-32767

**Comment by bradbehle** [comment]
@john-d-burke I don't think the extra rules you described above are the rules you want.  First I would use the Openshift specific docs for ACLs and Security Groups, which can be found here: https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy instead of the link you added above which is IKS specific.  The third rule down in each of the ACL tables in that doc, "Multizone clusters: Allow worker nodes in one subnet to communicate with the worker nodes in other subnets within the cluster. Create one rule for each subnet that you want to connect to." is the one that should allow workers in one subnet to talk to workers in a different subnet.

Also, @kersten1 is working on a few updates to the ACL rules that might also solve what you're seeing
