### ISSUE TITLE
service yaml definition incorrect

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/containers#2652]
https://cloud.ibm.com/docs/containers?topic=containers-vpc-lbaas#setup_vpc_nlb_priv

https port specification is incomplete
  ports:
   - name: http
     protocol: TCP
     port: 8080
     targetPort: 8080
   - name: https
     protocol: TCP
     port: 443

**Comment by marissa-treible** [comment]
Hi @lluissabarich

Thanks for opening this issue. The targetPort value is optional. By default it is set to match the port value. [Here's a link](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service) to the Kubernetes docs for more info. 

Since we recently had a similar issue opened, I've added a note to each LB service definition mentioning that the targetPort is optional. 

```
name: http
protocol: TCP
port: 8080
targetPort: 8080 # Optional. By default, the `targetPort` is set to match the `port` value unless specified otherwise.
```

Thanks again.
